version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
    ports:
       - "3306:3306"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8082:8080"
    volumes:
      - jenkins-data:/var/jenkins_home

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro


networks:
  mynetwork:

volumes:
  jenkins-data:


